### ISSUE TITLE
Some weapon models

### ISSUE THREAD

**Issue by Blakintosh** [dtzxporter/CommunityNameDB#3]
Credit goes to Raptroes for getting these models, I just sorted them into format and gave them the naming. Subject to errors or inconsistency.

```
HashedName,AssignedName
419bc60e5e678c8d,wpn_t8_kn57_view
47533d29ecbb32ac,attach_t8_kn57_adv_mag_view
4b9ce4081b792167,attach_t8_kn57_adv_mag_view
4a7568851a0264b8,wpn_t8_icr7_world_prop_animate
4ead7e0cf1be186f,wpn_t8_icr7_view
598d9840436e7dfa,wpn_t8_rampart17_view
641f5ca97d7697b2,attach_t8_optic_reflex_pistol_world
6ad5af7197e7f3e5,wpn_t8_koshka_world_prop_animate
6c3e349762f959c9,wpn_t8_spitfire_view
770717856fcd1584,wpn_t8_paladin_hb50_view
7b2fb354a4e97d87,wpn_t8_rampart17_world
7fabcbbbf8f160b7,wpn_t8_hero_grenade_launcher_view
f298754b73b7362,wpn_t8_hero_grenade_launcher_world
```

Buy 2 badly formatted posts, get a third free!

**Comment by iAmThatMichael** [comment]
Please merge them into the first issue instead of making individual ones.

i.e. additions that are 100% known without the missing ones go into the first thread while the unknowns go in unknown, feel like that'll make it easier to see from everyone involved.
